// Shared TypeScript types — imported by both frontend and backend

export interface Program {
  id: string
  name: string
  faculty: 'Science' | 'Social Sciences' | 'Humanities' | 'Arts & Letters'
  totalCredits: number
  description: string
}

export interface Course {
  id: string
  code: string
  crossListedCode?: string
  name: string
  credits: number
  programId: string
  faculty: string
  subjectPrefix: string
  year: number
  isRequired: boolean
  prerequisites: string[]
  corequisites: string[]
  semestersOffered: string[]
  offeringFrequency: 'every_semester' | 'every_year' | 'every_two_years'
  lastOfferedYear?: number
  careerTags: string[]
  minYearStanding: number
  programRestricted: boolean
  description: string
}

export interface Section {
  id: string
  courseId: string
  sectionCode: string
  type: 'lecture' | 'lab' | 'tutorial'
  semester: string
  days: string[]
  startTime: string
  endTime: string
  instructor: string
  room: string
  totalSeats: number
  enrolledCount: number
  waitlistCount: number
}

export interface Student {
  id: string
  name: string
  email: string
  programId: string
  startYear: number
  currentSemester: number
  standing: 'good' | 'probation'
  careerGoal?: string
  careerTags: string[]
  completedCourseIds: string[]
  failedCourseIds: string[]
  distributionChoices: Record<string, string>
}


export interface Enrollment {
  id: string
  studentId: string
  sectionId: string
  status: 'enrolled' | 'waitlisted' | 'dropped'
  registeredAt: string
  semester: string
}

export interface RegistrationWindow {
  id: string
  semester: string
  status: 'locked' | 'open' | 'completed'
  opensAt: string
  closesAt: string
}

// Stage 4 — result per section attempted
export type RegistrationStatus = 'enrolled' | 'waitlisted' | 'failed'

export interface SectionResult {
  sectionId: string
  courseCode: string
  status: RegistrationStatus
  reason?: string
}

export interface BundleResult {
  results: SectionResult[]
  partialFailure: boolean
  successfulIds: string[]
}

// Stage 2 — tracks how many slots and which prefixes are used per faculty category
export interface DistributionState {
  // faculty category → { filled count, prefix → count }
  slots: Record<string, { filled: number; prefixCounts: Record<string, number> }>
}

// Stage 2 output
export interface DistributionResult {
  assigned: Course[]
  distributionState: DistributionState
}

// Stage 3 output — conflict-free schedule options + coreq warnings
export interface CoreqWarning {
  courseCode: string          // course in the bundle
  missingCoreqCode: string    // co-req absent from the eligible set
}

export interface ScheduleResult {
  schedules: Section[][]
  canRegister: boolean
  canPreview: boolean
  message?: string
  suggestions?: string[]
  coreqWarnings?: CoreqWarning[]
}

// Stage 1 output — one entry per course Alex can still work toward
export interface CourseNode {
  course: Course
  depth: number        // 0 = prerequisites met (can take now), 1 = one semester away, etc.
  careerScore: number  // tag overlap count + out-degree bonus (gateway value)
}

// Stage 1 failed-course classification
export interface FailedCourseStatus {
  retakable: string[]  // course IDs offered this semester → include in schedule candidates
  delayed: Array<{ courseId: string; reason: string }>
  unreachable: string[]  // always [] in practice — kept for API completeness
}

// MtA Self-Service profile — shape returned by the university SIS
export interface MtaProfile {
  name:                 string
  program:              string
  standing:             'good' | 'probation'
  startYear:            number
  currentSemester:      number
  completedCourseCodes: string[]
  failedCourseCodes:    string[]
}

// Persisted draft plan — generated by the CSP solver, saved so the student can reload
export interface DraftPlan {
  id:        string
  studentId: string
  semester:  string
  schedules: Section[][]
  createdAt: string
  updatedAt: string
}
